config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :releases
  map.resources :projects
  map.resources :sprints
  
  map.new_project_release 'projects/:project_id/releases/new', :controller => 'releases', :action => 'new'
  map.new_project_ticket 'projects/:project_id/tickets/new', :controller => 'tickets', :action => 'new'
  
  map.resources :components
  map.resources :categories
  map.resources :synchronizers
  map.resources :schedule
  
  map.resources :activities
  map.tickets_update_all "/tickets", :controller => 'tickets', :action => 'update_all', :conditions => {:method => :put}
  map.resources :tickets
  
  map.login "sessions", :controller => 'sessions', :action => 'create', :conditions => {:method => :post}

  map.root :controller => 'projects'
end

app/models/lighthouse/project.rb
module Lighthouse
  class Project
    class << self
      def attributes_from_local(project)
        { #:id => project.remote_id, 
          :name => project.name, 
          :body => project.body }
      end
    end
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :components, :dependent => :destroy, :order => 'name'
  has_many :categories, :dependent => :destroy
  has_many :releases, :dependent => :destroy

  has_many :memberships, :dependent => :destroy
  has_many :members, :through => :memberships, :source => :user
  
  has_many :sprints, :dependent => :destroy do
    def unassigned
      find :all, :conditions => {:release_id => nil}
    end
  end
  
  has_many :tickets, :include => [:project, :release, :user], 
                     :order => 'milestones.name DESC, sprint_id DESC, tickets.state, tickets.priority, tickets.remote_id DESC, tickets.parent_id', 
                     :dependent => :destroy

  def remote_id(project_id = nil)
    self[:remote_id]
  end
  
  def synchronizer
    @synchronizer ||= Synchronizer.new self
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :set_project, :except => :index
  before_filter :set_filter, :only => :show
  before_filter :set_tickets, :only => :show

  def index
    @projects = Project.all
    @sprints = Sprint.all :order => "name DESC"
  end

  def show
  end

  def new
  end

  def create
    if @project.save
      flash[:notice] = 'Project has been created.'
      redirect_to(@project)
    else
      render :action => "new"
    end
  end

  def edit
    @users = User.all
  end

  def update
    if @project.update_attributes(params[:project])
      flash[:notice] = 'Project has been updated.'
      redirect_to(@project)
    else
      render :action => "edit"
    end
  end

  def destroy
    @project.destroy
    redirect_to(projects_url)
  end
  
  protected
  
    def set_project
      @project = params[:id] ? Project.find(params[:id]) : Project.new(params[:project])
    end
    
    def set_tickets
      @tickets = @project.tickets.find :all, :conditions => @filter.sql
    end
    
    def set_filter
      @filter = TicketListFilter.new @project, params[:filter]
    end
end

app/views/projects/_form.html.erb
<%= f.error_messages %>

<fieldset>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
</fieldset>

<fieldset>
  <legend>Lighthouse</legend>
  <p>
    <%= f.label :remote_id, 'Project id' %>
    <%= f.text_field :remote_id %>
  </p>
  <p>
    <%= f.label :lighthouse_account, 'Account' %>
    <%= f.text_field :lighthouse_account %>
  </p>
  <p>
    <%= f.label :lighthouse_token, 'Token' %>
    <%= f.text_field :lighthouse_token %>
  </p>
</fieldset>

app/views/projects/_member_select.html.erb
<% if (members = all_projects_members).any? %>
  <form action="<%= login_path %>" method="post">
    <%= hidden_field_tag :return_to, request.request_uri %>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <%= collection_select :current_user, :id, members, :id, :first_name, {:prompt => 'Current user'}, :onchange => "this.form.submit()" %>
  </form>
<% end %>

app/views/projects/_members.html.erb
<h1>Memberships</h1>

<% form_for @project do |f| %>
  <% @users.each do |user| %>
    <p>
      <%= check_box_tag "project[member_ids][]", user.id, @project.members.include?(user), :id => "project_member_ids_#{user.id}" %>
      <label id="project_member_ids_#{user.id}"><%= user.name %></label>
    </p>
  <% end %>
  <p class="buttons">
    <%= f.submit 'Save memberships' %>
  </p>
<% end %>

app/views/projects/edit.html.erb
<div id="breadcrumbs">
  <%= link_to 'Overview', projects_path %> »
  <%= link_to h(@project.name), @project %>
</div>

<h1>Settings</h1>

<% form_for(@project) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <p>
    <%= f.submit "Update" %> or <%= link_to 'back', @project %>
  </p>
<% end %>

<br>
<%= render :partial => "releases/list", :locals => {:components => @project.components } %>
<br>
<%= render :partial => "components/list", :locals => {:components => @project.components } %>
<br>
<%= render :partial => "categories/list", :locals => {:categories => @project.categories } %>
<br>
<%= render :partial => "members" %>

app/views/projects/index.html.erb
<h1>Projects</h1>

<p><%= link_to 'new project', new_project_path %></p>

<ul>
<% @projects.each do |project| %>
  <li><%= link_to h(project.name), project %></li>
<% end %>
</ul>


<h1>Sprints</h1>

<p>
  <%= link_to 'new sprint', new_sprint_path %>
</p>

<ul>
<% @sprints.each do |sprint| %>
  <li><%= link_to h(sprint.name), sprint %></li>
<% end %>
</ul>

<h1>Team</h1>

<%= link_to 'Schedule', schedule_index_path %>

app/views/projects/new.html.erb
<p>
  <%= link_to 'Overview', projects_path %> »
  New project
</p>

<h1>New project</h1>

<% form_for(@project) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <p>
    <%= f.submit "Create" %> or <%= link_to 'back', projects_path %>
  </p>
<% end %>

app/views/projects/show.html.erb
<div id="breadcrumbs">
  <%= link_to 'Overview', projects_path %> »
  <%=h @project.name %>
</div>

<div id="action">
  <%= link_to 'new ticket', new_project_ticket_path(@project) %> &middot;
  <%= link_to 'pull', synchronizers_path(:project_id => @project.id), :method => :post %> &middot;
  <%= link_to 'edit', edit_project_path(@project) %> &middot;
  <%= link_to 'destroy', @project, :confirm => 'Are you sure?', :method => :delete %>
</div>

<%= render :partial => 'tickets/filter' %>
<%= render :partial => "tickets/list", :locals => {:tickets => @tickets, :tracking => false, :headline => 'Project backlog' } %>